version: "1.0"
info:
  model: int-scaffold
packages:
- name: ProjectCreationProject
  gitServerName: rajka
  gitUrl: https://github.com/rajkapoor-rajkapoor
  gitUsername: rajkapoor-rajkapoor
  gitBranch: main
services:
- serviceName: project.projectcreation.integrations:DAFUsingVault
  packages:
  - name: ProjectCreationProject
    version: "1.0"
- serviceName: pub.math:addInts
  packages:
  - name: WmPublic
    version: 11.1.0.0.2047
- serviceName: project.projectcreation.integrations:dssd
  packages:
  - name: ProjectCreationProject
    version: "1.0"
- serviceName: pub.flow:setCustomContextID
  packages:
  - name: WmPublic
    version: 11.1.0.0.2047
