version: "1.0"
info:
  model: int-scaffold
packages:
- name: ProjectCreationProject
  gitServerName: rajka
  gitUrl: https://github.com/rajkapoor-rajkapoor
  gitUsername: rajkapoor-rajkapoor
  gitBranch: main
- name: aTest_Caching
  version: "1.0"
  gitServerName: rajka
  gitUrl: https://github.com/rajkapoor-rajkapoor
  gitUsername: rajkapoor-rajkapoor
  gitBranch: main
services:
- serviceName: project.projectcreation.integrations:DAFService
  packages:
  - name: ProjectCreationProject
    version: "1.0"
  - name: aTest_Caching
    version: "1.0"
- serviceName: pub.math:addInts
  packages:
  - name: WmPublic
    version: 11.1.0.0.2055
- serviceName: pub.flow:setHTTPResponse
  packages:
  - name: WmPublic
    version: 11.1.0.0.2055
- serviceName: project.projectcreation.integrations:DAFSs
  packages:
  - name: ProjectCreationProject
    version: "1.0"
  - name: aTest_Caching
    version: "1.0"
- serviceName: project.projectcreation.integrations:DAFUsingSetresponse
  packages:
  - name: ProjectCreationProject
    version: "1.0"
  - name: aTest_Caching
    version: "1.0"
- serviceName: project.projectcreation.integrations:DAFUsingVault
  packages:
  - name: ProjectCreationProject
    version: "1.0"
  - name: aTest_Caching
    version: "1.0"
- serviceName: project.projectcreation.integrations:DAFservice
  packages:
  - name: ProjectCreationProject
    version: "1.0"
  - name: aTest_Caching
    version: "1.0"
- serviceName: project.projectcreation.integrations:TestDAF
  packages:
  - name: ProjectCreationProject
    version: "1.0"
  - name: aTest_Caching
    version: "1.0"
- serviceName: pub.string:isNumber
  packages:
  - name: WmPublic
    version: 11.1.0.0.2055
- serviceName: project.projectcreation.integrations:dssd
  packages:
  - name: ProjectCreationProject
    version: "1.0"
  - name: aTest_Caching
    version: "1.0"
- serviceName: pub.flow:setCustomContextID
  packages:
  - name: WmPublic
    version: 11.1.0.0.2055
